### ISSUE TITLE
Ίρις - Ίριδα

### ISSUE THREAD

**Issue by chrispanag** [chrispanag/greek-name-klitiki#7]
This test fails, but I'm not sure if we want to add this kind of rule. Ίρις is acceptable. 

What do you think? @pappasadrian

**Comment by pappasadrian** [comment]
It is acceptable indeed, it is a matter of linguistic preference, ie how modern vs classical you want the overall language feel to be.

**Comment by chrispanag** [comment]
Let's not touch this issue for now then
